/** Don't edit manually. Generated by script: ./tools/icons/generate-imports.ts */
import airport_14 from '../../static/icons/airport_14.svg';
import airport_24 from '../../static/icons/airport_24.svg';
import attraction_14 from '../../static/icons/attraction_14.svg';
import attraction_24 from '../../static/icons/attraction_24.svg';
import auto_14 from '../../static/icons/auto_14.svg';
import auto_24 from '../../static/icons/auto_24.svg';
import aviary_24 from '../../static/icons/aviary_24.svg';
import baby_shop_14 from '../../static/icons/baby_shop_14.svg';
import baby_shop_24 from '../../static/icons/baby_shop_24.svg';
import banks_14 from '../../static/icons/banks_14.svg';
import banks_24 from '../../static/icons/banks_24.svg';
import barbeque_24 from '../../static/icons/barbeque_24.svg';
import bars_14 from '../../static/icons/bars_14.svg';
import bars_24 from '../../static/icons/bars_24.svg';
import beach_14 from '../../static/icons/beach_14.svg';
import beach_24 from '../../static/icons/beach_24.svg';
import bench_24 from '../../static/icons/bench_24.svg';
import bike_24 from '../../static/icons/bike_24.svg';
import bike_rent_14 from '../../static/icons/bike_rent_14.svg';
import bike_rent_24 from '../../static/icons/bike_rent_24.svg';
import boat_station_14 from '../../static/icons/boat_station_14.svg';
import boat_station_24 from '../../static/icons/boat_station_24.svg';
import bookstore_14 from '../../static/icons/bookstore_14.svg';
import bookstore_24 from '../../static/icons/bookstore_24.svg';
import buddhism_14 from '../../static/icons/buddhism_14.svg';
import buddhism_24 from '../../static/icons/buddhism_24.svg';
import building_24 from '../../static/icons/building_24.svg';
import bus_24 from '../../static/icons/bus_24.svg';
import cafe_14 from '../../static/icons/cafe_14.svg';
import cafe_24 from '../../static/icons/cafe_24.svg';
import car_park_24 from '../../static/icons/car_park_24.svg';
import catholic_church_14 from '../../static/icons/catholic_church_14.svg';
import catholic_church_24 from '../../static/icons/catholic_church_24.svg';
import cemetery_14 from '../../static/icons/cemetery_14.svg';
import cemetery_24 from '../../static/icons/cemetery_24.svg';
import childrens_playground_24 from '../../static/icons/childrens_playground_24.svg';
import cinemas_14 from '../../static/icons/cinemas_14.svg';
import cinemas_24 from '../../static/icons/cinemas_24.svg';
import clothes_shop_14 from '../../static/icons/clothes_shop_14.svg';
import clothes_shop_24 from '../../static/icons/clothes_shop_24.svg';
import college_14 from '../../static/icons/college_14.svg';
import college_24 from '../../static/icons/college_24.svg';
import concert_hall_14 from '../../static/icons/concert_hall_14.svg';
import concert_hall_24 from '../../static/icons/concert_hall_24.svg';
import confectionary_14 from '../../static/icons/confectionary_14.svg';
import confectionary_24 from '../../static/icons/confectionary_24.svg';
import currency_exchange_14 from '../../static/icons/currency_exchange_14.svg';
import currency_exchange_24 from '../../static/icons/currency_exchange_24.svg';
import dental_14 from '../../static/icons/dental_14.svg';
import dental_24 from '../../static/icons/dental_24.svg';
import driving_school_14 from '../../static/icons/driving_school_14.svg';
import driving_school_24 from '../../static/icons/driving_school_24.svg';
import drugstores_14 from '../../static/icons/drugstores_14.svg';
import drugstores_24 from '../../static/icons/drugstores_24.svg';
import dry_cleaning_14 from '../../static/icons/dry_cleaning_14.svg';
import dry_cleaning_24 from '../../static/icons/dry_cleaning_24.svg';
import equestrian_14 from '../../static/icons/equestrian_14.svg';
import equestrian_24 from '../../static/icons/equestrian_24.svg';
import fallback_14 from '../../static/icons/fallback_14.svg';
import fallback_24 from '../../static/icons/fallback_24.svg';
import fast_food_14 from '../../static/icons/fast_food_14.svg';
import fast_food_24 from '../../static/icons/fast_food_24.svg';
import film_studio_14 from '../../static/icons/film_studio_14.svg';
import film_studio_24 from '../../static/icons/film_studio_24.svg';
import fire_station_14 from '../../static/icons/fire_station_14.svg';
import fire_station_24 from '../../static/icons/fire_station_24.svg';
import fitness_14 from '../../static/icons/fitness_14.svg';
import fitness_24 from '../../static/icons/fitness_24.svg';
import flower_shop_14 from '../../static/icons/flower_shop_14.svg';
import flower_shop_24 from '../../static/icons/flower_shop_24.svg';
import forest_14 from '../../static/icons/forest_14.svg';
import forest_24 from '../../static/icons/forest_24.svg';
import fountain_24 from '../../static/icons/fountain_24.svg';
import furniture_store_14 from '../../static/icons/furniture_store_14.svg';
import furniture_store_24 from '../../static/icons/furniture_store_24.svg';
import garden_14 from '../../static/icons/garden_14.svg';
import garden_24 from '../../static/icons/garden_24.svg';
import gasstation_14 from '../../static/icons/gasstation_14.svg';
import gasstation_24 from '../../static/icons/gasstation_24.svg';
import government_14 from '../../static/icons/government_14.svg';
import government_24 from '../../static/icons/government_24.svg';
import hairdressers_14 from '../../static/icons/hairdressers_14.svg';
import hairdressers_24 from '../../static/icons/hairdressers_24.svg';
import haulier_14 from '../../static/icons/haulier_14.svg';
import haulier_24 from '../../static/icons/haulier_24.svg';
import helicopter_24 from '../../static/icons/helicopter_24.svg';
import hospital_14 from '../../static/icons/hospital_14.svg';
import hospital_24 from '../../static/icons/hospital_24.svg';
import hotels_14 from '../../static/icons/hotels_14.svg';
import hotels_24 from '../../static/icons/hotels_24.svg';
import hypermarket_14 from '../../static/icons/hypermarket_14.svg';
import hypermarket_24 from '../../static/icons/hypermarket_24.svg';
import industrial_enterprise_14 from '../../static/icons/industrial_enterprise_14.svg';
import industrial_enterprise_24 from '../../static/icons/industrial_enterprise_24.svg';
import information_14 from '../../static/icons/information_14.svg';
import information_24 from '../../static/icons/information_24.svg';
import kindergarten_14 from '../../static/icons/kindergarten_14.svg';
import kindergarten_24 from '../../static/icons/kindergarten_24.svg';
import landmark_14 from '../../static/icons/landmark_14.svg';
import landmark_24 from '../../static/icons/landmark_24.svg';
import laundry_14 from '../../static/icons/laundry_14.svg';
import laundry_24 from '../../static/icons/laundry_24.svg';
import library_14 from '../../static/icons/library_14.svg';
import library_24 from '../../static/icons/library_24.svg';
import malls_14 from '../../static/icons/malls_14.svg';
import malls_24 from '../../static/icons/malls_24.svg';
import medicine_14 from '../../static/icons/medicine_14.svg';
import medicine_24 from '../../static/icons/medicine_24.svg';
import memorable_event_14 from '../../static/icons/memorable_event_14.svg';
import memorable_event_24 from '../../static/icons/memorable_event_24.svg';
import metro_14 from '../../static/icons/metro_14.svg';
import metro_24 from '../../static/icons/metro_24.svg';
import metro_bus_14 from '../../static/icons/metro_bus_14.svg';
import metro_bus_24 from '../../static/icons/metro_bus_24.svg';
import metro_cable_14 from '../../static/icons/metro_cable_14.svg';
import metro_cable_24 from '../../static/icons/metro_cable_24.svg';
import metro_entrance_24 from '../../static/icons/metro_entrance_24.svg';
import metro_funicular_14 from '../../static/icons/metro_funicular_14.svg';
import metro_funicular_24 from '../../static/icons/metro_funicular_24.svg';
import metro_light_14 from '../../static/icons/metro_light_14.svg';
import metro_light_24 from '../../static/icons/metro_light_24.svg';
import metro_monorail_14 from '../../static/icons/metro_monorail_14.svg';
import metro_monorail_24 from '../../static/icons/metro_monorail_24.svg';
import metro_tram_14 from '../../static/icons/metro_tram_14.svg';
import metro_tram_24 from '../../static/icons/metro_tram_24.svg';
import mobile_phones_14 from '../../static/icons/mobile_phones_14.svg';
import mobile_phones_24 from '../../static/icons/mobile_phones_24.svg';
import money_coin_24 from '../../static/icons/money_coin_24.svg';
import monument_24 from '../../static/icons/monument_24.svg';
import mosque_14 from '../../static/icons/mosque_14.svg';
import mosque_24 from '../../static/icons/mosque_24.svg';
import mountain_24 from '../../static/icons/mountain_24.svg';
import museum_14 from '../../static/icons/museum_14.svg';
import museum_24 from '../../static/icons/museum_24.svg';
import office_14 from '../../static/icons/office_14.svg';
import office_24 from '../../static/icons/office_24.svg';
import office_service_14 from '../../static/icons/office_service_14.svg';
import office_service_24 from '../../static/icons/office_service_24.svg';
import orthodox_church_14 from '../../static/icons/orthodox_church_14.svg';
import orthodox_church_24 from '../../static/icons/orthodox_church_24.svg';
import park_14 from '../../static/icons/park_14.svg';
import park_24 from '../../static/icons/park_24.svg';
import pavilion_24 from '../../static/icons/pavilion_24.svg';
import pet_playground_24 from '../../static/icons/pet_playground_24.svg';
import petshop_14 from '../../static/icons/petshop_14.svg';
import petshop_24 from '../../static/icons/petshop_24.svg';
import photo_14 from '../../static/icons/photo_14.svg';
import photo_24 from '../../static/icons/photo_24.svg';
import picnic_24 from '../../static/icons/picnic_24.svg';
import pier_24 from '../../static/icons/pier_24.svg';
import playground_24 from '../../static/icons/playground_24.svg';
import police_14 from '../../static/icons/police_14.svg';
import police_24 from '../../static/icons/police_24.svg';
import police_post_14 from '../../static/icons/police_post_14.svg';
import police_post_24 from '../../static/icons/police_post_24.svg';
import port_14 from '../../static/icons/port_14.svg';
import port_24 from '../../static/icons/port_24.svg';
import post_office_14 from '../../static/icons/post_office_14.svg';
import post_office_24 from '../../static/icons/post_office_24.svg';
import printing_services_14 from '../../static/icons/printing_services_14.svg';
import printing_services_24 from '../../static/icons/printing_services_24.svg';
import protestant_church_14 from '../../static/icons/protestant_church_14.svg';
import protestant_church_24 from '../../static/icons/protestant_church_24.svg';
import racing_14 from '../../static/icons/racing_14.svg';
import racing_24 from '../../static/icons/racing_24.svg';
import railway_14 from '../../static/icons/railway_14.svg';
import railway_24 from '../../static/icons/railway_24.svg';
import railway_station_14 from '../../static/icons/railway_station_14.svg';
import railway_station_24 from '../../static/icons/railway_station_24.svg';
import recycling_24 from '../../static/icons/recycling_24.svg';
import restaurants_14 from '../../static/icons/restaurants_14.svg';
import restaurants_24 from '../../static/icons/restaurants_24.svg';
import rezervation_14 from '../../static/icons/rezervation_14.svg';
import rezervation_24 from '../../static/icons/rezervation_24.svg';
import sanatorium_14 from '../../static/icons/sanatorium_14.svg';
import sanatorium_24 from '../../static/icons/sanatorium_24.svg';
import science_14 from '../../static/icons/science_14.svg';
import science_24 from '../../static/icons/science_24.svg';
import skating_rink_14 from '../../static/icons/skating_rink_14.svg';
import skating_rink_24 from '../../static/icons/skating_rink_24.svg';
import software_14 from '../../static/icons/software_14.svg';
import software_24 from '../../static/icons/software_24.svg';
import spa_14 from '../../static/icons/spa_14.svg';
import spa_24 from '../../static/icons/spa_24.svg';
import sportcenter_14 from '../../static/icons/sportcenter_14.svg';
import sportcenter_24 from '../../static/icons/sportcenter_24.svg';
import spring_24 from '../../static/icons/spring_24.svg';
import stadium_14 from '../../static/icons/stadium_14.svg';
import stadium_24 from '../../static/icons/stadium_24.svg';
import supermarket_14 from '../../static/icons/supermarket_14.svg';
import supermarket_24 from '../../static/icons/supermarket_24.svg';
import sushi_14 from '../../static/icons/sushi_14.svg';
import sushi_24 from '../../static/icons/sushi_24.svg';
import swimming_pool_14 from '../../static/icons/swimming_pool_14.svg';
import swimming_pool_24 from '../../static/icons/swimming_pool_24.svg';
import synagogue_14 from '../../static/icons/synagogue_14.svg';
import synagogue_24 from '../../static/icons/synagogue_24.svg';
import tailor_14 from '../../static/icons/tailor_14.svg';
import tailor_24 from '../../static/icons/tailor_24.svg';
import taxi_14 from '../../static/icons/taxi_14.svg';
import taxi_24 from '../../static/icons/taxi_24.svg';
import theatre_14 from '../../static/icons/theatre_14.svg';
import theatre_24 from '../../static/icons/theatre_24.svg';
import ticket_office_14 from '../../static/icons/ticket_office_14.svg';
import ticket_office_24 from '../../static/icons/ticket_office_24.svg';
import tire_fitting_14 from '../../static/icons/tire_fitting_14.svg';
import tire_fitting_24 from '../../static/icons/tire_fitting_24.svg';
import tram_24 from '../../static/icons/tram_24.svg';
import trash_24 from '../../static/icons/trash_24.svg';
import travel_agency_14 from '../../static/icons/travel_agency_14.svg';
import travel_agency_24 from '../../static/icons/travel_agency_24.svg';
import viewpoint_24 from '../../static/icons/viewpoint_24.svg';
import waterfall_24 from '../../static/icons/waterfall_24.svg';
import wc_24 from '../../static/icons/wc_24.svg';
import zoo_14 from '../../static/icons/zoo_14.svg';
import zoo_24 from '../../static/icons/zoo_24.svg';

import type {Icons} from './types';
export const icons: Icons = {
  airport: {normal: airport_24, small: airport_14},
  attraction: {normal: attraction_24, small: attraction_14},
  auto: {normal: auto_24, small: auto_14},
  aviary: {normal: aviary_24, small: null},
  baby_shop: {normal: baby_shop_24, small: baby_shop_14},
  banks: {normal: banks_24, small: banks_14},
  barbeque: {normal: barbeque_24, small: null},
  bars: {normal: bars_24, small: bars_14},
  beach: {normal: beach_24, small: beach_14},
  bench: {normal: bench_24, small: null},
  bike: {normal: bike_24, small: null},
  bike_rent: {normal: bike_rent_24, small: bike_rent_14},
  boat_station: {normal: boat_station_24, small: boat_station_14},
  bookstore: {normal: bookstore_24, small: bookstore_14},
  buddhism: {normal: buddhism_24, small: buddhism_14},
  building: {normal: building_24, small: null},
  bus: {normal: bus_24, small: null},
  cafe: {normal: cafe_24, small: cafe_14},
  car_park: {normal: car_park_24, small: null},
  catholic_church: {normal: catholic_church_24, small: catholic_church_14},
  cemetery: {normal: cemetery_24, small: cemetery_14},
  childrens_playground: {normal: childrens_playground_24, small: null},
  cinemas: {normal: cinemas_24, small: cinemas_14},
  clothes_shop: {normal: clothes_shop_24, small: clothes_shop_14},
  college: {normal: college_24, small: college_14},
  concert_hall: {normal: concert_hall_24, small: concert_hall_14},
  confectionary: {normal: confectionary_24, small: confectionary_14},
  currency_exchange: {normal: currency_exchange_24, small: currency_exchange_14},
  dental: {normal: dental_24, small: dental_14},
  driving_school: {normal: driving_school_24, small: driving_school_14},
  drugstores: {normal: drugstores_24, small: drugstores_14},
  dry_cleaning: {normal: dry_cleaning_24, small: dry_cleaning_14},
  equestrian: {normal: equestrian_24, small: equestrian_14},
  fallback: {normal: fallback_24, small: fallback_14},
  fast_food: {normal: fast_food_24, small: fast_food_14},
  film_studio: {normal: film_studio_24, small: film_studio_14},
  fire_station: {normal: fire_station_24, small: fire_station_14},
  fitness: {normal: fitness_24, small: fitness_14},
  flower_shop: {normal: flower_shop_24, small: flower_shop_14},
  forest: {normal: forest_24, small: forest_14},
  fountain: {normal: fountain_24, small: null},
  furniture_store: {normal: furniture_store_24, small: furniture_store_14},
  garden: {normal: garden_24, small: garden_14},
  gasstation: {normal: gasstation_24, small: gasstation_14},
  government: {normal: government_24, small: government_14},
  hairdressers: {normal: hairdressers_24, small: hairdressers_14},
  haulier: {normal: haulier_24, small: haulier_14},
  helicopter: {normal: helicopter_24, small: null},
  hospital: {normal: hospital_24, small: hospital_14},
  hotels: {normal: hotels_24, small: hotels_14},
  hypermarket: {normal: hypermarket_24, small: hypermarket_14},
  industrial_enterprise: {normal: industrial_enterprise_24, small: industrial_enterprise_14},
  information: {normal: information_24, small: information_14},
  kindergarten: {normal: kindergarten_24, small: kindergarten_14},
  landmark: {normal: landmark_24, small: landmark_14},
  laundry: {normal: laundry_24, small: laundry_14},
  library: {normal: library_24, small: library_14},
  malls: {normal: malls_24, small: malls_14},
  medicine: {normal: medicine_24, small: medicine_14},
  memorable_event: {normal: memorable_event_24, small: memorable_event_14},
  metro: {normal: metro_24, small: metro_14},
  metro_bus: {normal: metro_bus_24, small: metro_bus_14},
  metro_cable: {normal: metro_cable_24, small: metro_cable_14},
  metro_entrance: {normal: metro_entrance_24, small: null},
  metro_funicular: {normal: metro_funicular_24, small: metro_funicular_14},
  metro_light: {normal: metro_light_24, small: metro_light_14},
  metro_monorail: {normal: metro_monorail_24, small: metro_monorail_14},
  metro_tram: {normal: metro_tram_24, small: metro_tram_14},
  mobile_phones: {normal: mobile_phones_24, small: mobile_phones_14},
  money_coin: {normal: money_coin_24, small: null},
  monument: {normal: monument_24, small: null},
  mosque: {normal: mosque_24, small: mosque_14},
  mountain: {normal: mountain_24, small: null},
  museum: {normal: museum_24, small: museum_14},
  office: {normal: office_24, small: office_14},
  office_service: {normal: office_service_24, small: office_service_14},
  orthodox_church: {normal: orthodox_church_24, small: orthodox_church_14},
  park: {normal: park_24, small: park_14},
  pavilion: {normal: pavilion_24, small: null},
  pet_playground: {normal: pet_playground_24, small: null},
  petshop: {normal: petshop_24, small: petshop_14},
  photo: {normal: photo_24, small: photo_14},
  picnic: {normal: picnic_24, small: null},
  pier: {normal: pier_24, small: null},
  playground: {normal: playground_24, small: null},
  police: {normal: police_24, small: police_14},
  police_post: {normal: police_post_24, small: police_post_14},
  port: {normal: port_24, small: port_14},
  post_office: {normal: post_office_24, small: post_office_14},
  printing_services: {normal: printing_services_24, small: printing_services_14},
  protestant_church: {normal: protestant_church_24, small: protestant_church_14},
  racing: {normal: racing_24, small: racing_14},
  railway: {normal: railway_24, small: railway_14},
  railway_station: {normal: railway_station_24, small: railway_station_14},
  recycling: {normal: recycling_24, small: null},
  restaurants: {normal: restaurants_24, small: restaurants_14},
  rezervation: {normal: rezervation_24, small: rezervation_14},
  sanatorium: {normal: sanatorium_24, small: sanatorium_14},
  science: {normal: science_24, small: science_14},
  skating_rink: {normal: skating_rink_24, small: skating_rink_14},
  software: {normal: software_24, small: software_14},
  spa: {normal: spa_24, small: spa_14},
  sportcenter: {normal: sportcenter_24, small: sportcenter_14},
  spring: {normal: spring_24, small: null},
  stadium: {normal: stadium_24, small: stadium_14},
  supermarket: {normal: supermarket_24, small: supermarket_14},
  sushi: {normal: sushi_24, small: sushi_14},
  swimming_pool: {normal: swimming_pool_24, small: swimming_pool_14},
  synagogue: {normal: synagogue_24, small: synagogue_14},
  tailor: {normal: tailor_24, small: tailor_14},
  taxi: {normal: taxi_24, small: taxi_14},
  theatre: {normal: theatre_24, small: theatre_14},
  ticket_office: {normal: ticket_office_24, small: ticket_office_14},
  tire_fitting: {normal: tire_fitting_24, small: tire_fitting_14},
  tram: {normal: tram_24, small: null},
  trash: {normal: trash_24, small: null},
  travel_agency: {normal: travel_agency_24, small: travel_agency_14},
  viewpoint: {normal: viewpoint_24, small: null},
  waterfall: {normal: waterfall_24, small: null},
  wc: {normal: wc_24, small: null},
  zoo: {normal: zoo_24, small: zoo_14}
};
