/** Don't edit manually. Generated by script: ./tools/icons/generate-imports.ts */
import airport_24 from '../../static/icons/airport_24.svg';
import attraction_24 from '../../static/icons/attraction_24.svg';
import auto_24 from '../../static/icons/auto_24.svg';
import aviary_24 from '../../static/icons/aviary_24.svg';
import baby_shop_24 from '../../static/icons/baby_shop_24.svg';
import banks_24 from '../../static/icons/banks_24.svg';
import barbeque_24 from '../../static/icons/barbeque_24.svg';
import bars_24 from '../../static/icons/bars_24.svg';
import beach_24 from '../../static/icons/beach_24.svg';
import bench_24 from '../../static/icons/bench_24.svg';
import bike_24 from '../../static/icons/bike_24.svg';
import bike_rent_24 from '../../static/icons/bike_rent_24.svg';
import boat_station_24 from '../../static/icons/boat_station_24.svg';
import bookstore_24 from '../../static/icons/bookstore_24.svg';
import buddhism_24 from '../../static/icons/buddhism_24.svg';
import building_24 from '../../static/icons/building_24.svg';
import bus_24 from '../../static/icons/bus_24.svg';
import cafe_24 from '../../static/icons/cafe_24.svg';
import car_park_24 from '../../static/icons/car_park_24.svg';
import catholic_church_24 from '../../static/icons/catholic_church_24.svg';
import cemetery_24 from '../../static/icons/cemetery_24.svg';
import childrens_playground_24 from '../../static/icons/childrens_playground_24.svg';
import cinemas_24 from '../../static/icons/cinemas_24.svg';
import clothes_shop_24 from '../../static/icons/clothes_shop_24.svg';
import college_24 from '../../static/icons/college_24.svg';
import concert_hall_24 from '../../static/icons/concert_hall_24.svg';
import confectionary_24 from '../../static/icons/confectionary_24.svg';
import currency_exchange_24 from '../../static/icons/currency_exchange_24.svg';
import dental_24 from '../../static/icons/dental_24.svg';
import driving_school_24 from '../../static/icons/driving_school_24.svg';
import drugstores_24 from '../../static/icons/drugstores_24.svg';
import dry_cleaning_24 from '../../static/icons/dry_cleaning_24.svg';
import equestrian_24 from '../../static/icons/equestrian_24.svg';
import fallback_24 from '../../static/icons/fallback_24.svg';
import fast_food_24 from '../../static/icons/fast_food_24.svg';
import film_studio_24 from '../../static/icons/film_studio_24.svg';
import fire_station_24 from '../../static/icons/fire_station_24.svg';
import fitness_24 from '../../static/icons/fitness_24.svg';
import flower_shop_24 from '../../static/icons/flower_shop_24.svg';
import forest_24 from '../../static/icons/forest_24.svg';
import fountain_24 from '../../static/icons/fountain_24.svg';
import furniture_store_24 from '../../static/icons/furniture_store_24.svg';
import garden_24 from '../../static/icons/garden_24.svg';
import gasstation_24 from '../../static/icons/gasstation_24.svg';
import government_24 from '../../static/icons/government_24.svg';
import hairdressers_24 from '../../static/icons/hairdressers_24.svg';
import haulier_24 from '../../static/icons/haulier_24.svg';
import helicopter_24 from '../../static/icons/helicopter_24.svg';
import hospital_24 from '../../static/icons/hospital_24.svg';
import hotels_24 from '../../static/icons/hotels_24.svg';
import hypermarket_24 from '../../static/icons/hypermarket_24.svg';
import industrial_enterprise_24 from '../../static/icons/industrial_enterprise_24.svg';
import information_24 from '../../static/icons/information_24.svg';
import kindergarten_24 from '../../static/icons/kindergarten_24.svg';
import landmark_24 from '../../static/icons/landmark_24.svg';
import laundry_24 from '../../static/icons/laundry_24.svg';
import library_24 from '../../static/icons/library_24.svg';
import malls_24 from '../../static/icons/malls_24.svg';
import medicine_24 from '../../static/icons/medicine_24.svg';
import memorable_event_24 from '../../static/icons/memorable_event_24.svg';
import metro_24 from '../../static/icons/metro_24.svg';
import metro_bus_24 from '../../static/icons/metro_bus_24.svg';
import metro_cable_24 from '../../static/icons/metro_cable_24.svg';
import metro_entrance_24 from '../../static/icons/metro_entrance_24.svg';
import metro_funicular_24 from '../../static/icons/metro_funicular_24.svg';
import metro_light_24 from '../../static/icons/metro_light_24.svg';
import metro_monorail_24 from '../../static/icons/metro_monorail_24.svg';
import metro_tram_24 from '../../static/icons/metro_tram_24.svg';
import mobile_phones_24 from '../../static/icons/mobile_phones_24.svg';
import money_coin_24 from '../../static/icons/money_coin_24.svg';
import monument_24 from '../../static/icons/monument_24.svg';
import mosque_24 from '../../static/icons/mosque_24.svg';
import mountain_24 from '../../static/icons/mountain_24.svg';
import museum_24 from '../../static/icons/museum_24.svg';
import office_24 from '../../static/icons/office_24.svg';
import office_service_24 from '../../static/icons/office_service_24.svg';
import orthodox_church_24 from '../../static/icons/orthodox_church_24.svg';
import park_24 from '../../static/icons/park_24.svg';
import pavilion_24 from '../../static/icons/pavilion_24.svg';
import pet_playground_24 from '../../static/icons/pet_playground_24.svg';
import petshop_24 from '../../static/icons/petshop_24.svg';
import photo_24 from '../../static/icons/photo_24.svg';
import picnic_24 from '../../static/icons/picnic_24.svg';
import pier_24 from '../../static/icons/pier_24.svg';
import playground_24 from '../../static/icons/playground_24.svg';
import police_24 from '../../static/icons/police_24.svg';
import police_post_24 from '../../static/icons/police_post_24.svg';
import port_24 from '../../static/icons/port_24.svg';
import post_office_24 from '../../static/icons/post_office_24.svg';
import printing_services_24 from '../../static/icons/printing_services_24.svg';
import protestant_church_24 from '../../static/icons/protestant_church_24.svg';
import racing_24 from '../../static/icons/racing_24.svg';
import railway_24 from '../../static/icons/railway_24.svg';
import railway_station_24 from '../../static/icons/railway_station_24.svg';
import recycling_24 from '../../static/icons/recycling_24.svg';
import restaurants_24 from '../../static/icons/restaurants_24.svg';
import rezervation_24 from '../../static/icons/rezervation_24.svg';
import sanatorium_24 from '../../static/icons/sanatorium_24.svg';
import science_24 from '../../static/icons/science_24.svg';
import skating_rink_24 from '../../static/icons/skating_rink_24.svg';
import software_24 from '../../static/icons/software_24.svg';
import spa_24 from '../../static/icons/spa_24.svg';
import sportcenter_24 from '../../static/icons/sportcenter_24.svg';
import spring_24 from '../../static/icons/spring_24.svg';
import stadium_24 from '../../static/icons/stadium_24.svg';
import supermarket_24 from '../../static/icons/supermarket_24.svg';
import sushi_24 from '../../static/icons/sushi_24.svg';
import swimming_pool_24 from '../../static/icons/swimming_pool_24.svg';
import synagogue_24 from '../../static/icons/synagogue_24.svg';
import tailor_24 from '../../static/icons/tailor_24.svg';
import taxi_24 from '../../static/icons/taxi_24.svg';
import theatre_24 from '../../static/icons/theatre_24.svg';
import ticket_office_24 from '../../static/icons/ticket_office_24.svg';
import tire_fitting_24 from '../../static/icons/tire_fitting_24.svg';
import tram_24 from '../../static/icons/tram_24.svg';
import trash_24 from '../../static/icons/trash_24.svg';
import travel_agency_24 from '../../static/icons/travel_agency_24.svg';
import viewpoint_24 from '../../static/icons/viewpoint_24.svg';
import waterfall_24 from '../../static/icons/waterfall_24.svg';
import wc_24 from '../../static/icons/wc_24.svg';
import zoo_24 from '../../static/icons/zoo_24.svg';

import type {Icons} from './types';
export const icons: Icons = {
  airport: airport_24,
  attraction: attraction_24,
  auto: auto_24,
  aviary: aviary_24,
  baby_shop: baby_shop_24,
  banks: banks_24,
  barbeque: barbeque_24,
  bars: bars_24,
  beach: beach_24,
  bench: bench_24,
  bike: bike_24,
  bike_rent: bike_rent_24,
  boat_station: boat_station_24,
  bookstore: bookstore_24,
  buddhism: buddhism_24,
  building: building_24,
  bus: bus_24,
  cafe: cafe_24,
  car_park: car_park_24,
  catholic_church: catholic_church_24,
  cemetery: cemetery_24,
  childrens_playground: childrens_playground_24,
  cinemas: cinemas_24,
  clothes_shop: clothes_shop_24,
  college: college_24,
  concert_hall: concert_hall_24,
  confectionary: confectionary_24,
  currency_exchange: currency_exchange_24,
  dental: dental_24,
  driving_school: driving_school_24,
  drugstores: drugstores_24,
  dry_cleaning: dry_cleaning_24,
  equestrian: equestrian_24,
  fallback: fallback_24,
  fast_food: fast_food_24,
  film_studio: film_studio_24,
  fire_station: fire_station_24,
  fitness: fitness_24,
  flower_shop: flower_shop_24,
  forest: forest_24,
  fountain: fountain_24,
  furniture_store: furniture_store_24,
  garden: garden_24,
  gasstation: gasstation_24,
  government: government_24,
  hairdressers: hairdressers_24,
  haulier: haulier_24,
  helicopter: helicopter_24,
  hospital: hospital_24,
  hotels: hotels_24,
  hypermarket: hypermarket_24,
  industrial_enterprise: industrial_enterprise_24,
  information: information_24,
  kindergarten: kindergarten_24,
  landmark: landmark_24,
  laundry: laundry_24,
  library: library_24,
  malls: malls_24,
  medicine: medicine_24,
  memorable_event: memorable_event_24,
  metro: metro_24,
  metro_bus: metro_bus_24,
  metro_cable: metro_cable_24,
  metro_entrance: metro_entrance_24,
  metro_funicular: metro_funicular_24,
  metro_light: metro_light_24,
  metro_monorail: metro_monorail_24,
  metro_tram: metro_tram_24,
  mobile_phones: mobile_phones_24,
  money_coin: money_coin_24,
  monument: monument_24,
  mosque: mosque_24,
  mountain: mountain_24,
  museum: museum_24,
  office: office_24,
  office_service: office_service_24,
  orthodox_church: orthodox_church_24,
  park: park_24,
  pavilion: pavilion_24,
  pet_playground: pet_playground_24,
  petshop: petshop_24,
  photo: photo_24,
  picnic: picnic_24,
  pier: pier_24,
  playground: playground_24,
  police: police_24,
  police_post: police_post_24,
  port: port_24,
  post_office: post_office_24,
  printing_services: printing_services_24,
  protestant_church: protestant_church_24,
  racing: racing_24,
  railway: railway_24,
  railway_station: railway_station_24,
  recycling: recycling_24,
  restaurants: restaurants_24,
  rezervation: rezervation_24,
  sanatorium: sanatorium_24,
  science: science_24,
  skating_rink: skating_rink_24,
  software: software_24,
  spa: spa_24,
  sportcenter: sportcenter_24,
  spring: spring_24,
  stadium: stadium_24,
  supermarket: supermarket_24,
  sushi: sushi_24,
  swimming_pool: swimming_pool_24,
  synagogue: synagogue_24,
  tailor: tailor_24,
  taxi: taxi_24,
  theatre: theatre_24,
  ticket_office: ticket_office_24,
  tire_fitting: tire_fitting_24,
  tram: tram_24,
  trash: trash_24,
  travel_agency: travel_agency_24,
  viewpoint: viewpoint_24,
  waterfall: waterfall_24,
  wc: wc_24,
  zoo: zoo_24
};
