import fs from 'fs/promises';
import path from 'path';
import {prettierFormat} from '../utils/prettier-format';
import {BASE_DIR} from './local';

const TYPES_PATH = path.join(BASE_DIR, 'src/icons/types');

export const generateIconsTypes = async (iconNames: string[]) => {
    const type = 'IconName';
    const content = `
/** Don't edit manually. Generated by script: ./tools/icons/generate-types.ts */
type ${type} =${iconNames.map((name) => `| '${name}'`).join('\n')};

export {${type}};
`;
    const formattedContent = await prettierFormat(content, 'typescript');
    await fs.writeFile(path.join(TYPES_PATH, 'icons.ts'), formattedContent);
};
